### ISSUE TITLE
Forge: Light overlay renders through blocks

### ISSUE THREAD

**Issue by Naxanria** [shedaniel/LightOverlay-Fabric#26] opened 2020-03-06 22:04 UTC
![image](https://user-images.githubusercontent.com/3246224/76126186-c0d8ff80-5ffe-11ea-8a13-2df99027c0e0.png)

**Comment by shedaniel** [comment] 2020-03-07 07:05
Which minecraft / light overlay version?

**Comment by Naxanria** [comment] 2020-03-07 12:11
Minecraft: 1.15.2
Forge: 31.1.18
Overlay: 4.2

**Comment by shedaniel** [comment] 2020-03-07 13:14
Thanks, I will test with that configuration.

**Comment by shedaniel** [comment] 2020-03-07 16:23
I can't seem to be able to reproduce that issue, can you send the full log over?

**Comment by stop-x13** [comment] 2020-04-11 12:16
> I can't seem to be able to reproduce that issue, can you send the full log over?
![image](https://user-images.githubusercontent.com/59541513/79043250-7bcd6c00-7c41-11ea-934b-affe551053b0.png)

Same issue. Only this mod (and the library) are running.
Minecraft: 1.15.2
Forge: 31.1.43
Overlay: 4.3
ClothConfig2: 2.0

Numbers are fine, only the crosses render through blocks.

**Comment by shedaniel** [comment] 2020-04-11 12:50
Can you send the full log over?

**Comment by stop-x13** [comment] 2020-04-12 07:21
[latest.log](https://github.com/shedaniel/LightOverlay-Fabric/files/4465979/latest.log)
This is the log file. Do you need the debug.log as well?


> Can you send the full log over?

**Comment by shedaniel** [comment] 2020-04-12 07:30
Thanks.

**Comment by shedaniel** [comment] 2020-04-12 07:37
I still can't reproduce the issue, maybe it is a windows only bug, I will have to look into this.

**Comment by stop-x13** [comment] 2020-04-12 08:09
> I still can't reproduce the issue, maybe it is a windows only bug, I will have to look into this.

OK, I use windows 10. The strange thing is number mode looks fine, only the crosses have this bug. This might help.

**Comment by shedaniel** [comment] 2020-04-16 13:10
Can you send your PC specs so I can look into this further?

**Comment by Bass2style** [comment] 2020-04-16 17:18
i have the same issue here.

Minecraft related :
Forge : 31.1.46
Light Overlay : 4.3

PC Related : 
OS : Windows10
GPU : AMD R9 380X Nitro (driver : 19.50.19.01-200130a-351505E-RadeonSoftwareAdrenalin2020)
CPU : I5-4460

i can't give you my latest.log actually, because i have a 9hours playing session, so there is too much informations. XD

idk if it can help, but if i can provide more info, i should try to give it.

**Comment by shedaniel** [comment] 2020-04-16 17:21
Thanks, that specs would help, and also I don't think I need the logs anymore as they don't tell me a lot

**Comment by Bass2style** [comment] 2020-04-16 19:28
no problem. expecting that can help to find out what's the issue. ^^

**Comment by shedaniel** [comment] 2020-04-29 17:03
Please check if the latest update has the same issue, I changed when the overlay is rendered.

**Comment by Bass2style** [comment] 2020-05-01 18:10
it seems correct now, the only remaining "bug" that i found is that the overlay appairs over grass/plants, not on the dirt under it.

https://image.noelshack.com/fichiers/2020/18/5/1588356544-2020-05-01-19-50-03.png
https://image.noelshack.com/fichiers/2020/18/5/1588356544-2020-05-01-19-50-57.png
https://image.noelshack.com/fichiers/2020/18/5/1588356544-2020-05-01-19-58-32.png
https://image.noelshack.com/fichiers/2020/18/5/1588356545-2020-05-01-19-58-49.jpg

**Comment by shedaniel** [comment] 2020-05-01 18:19
That's another issue that #36 will hopefully fix, for now I will close this issue to keep this clean

**Closed as completed by shedaniel** 2020-05-01 18:19 UTC
Labels: bug, help wanted
