### ISSUE TITLE
Doesn't seem to work with Iris and/or Sodium

### ISSUE THREAD

**Issue by blackjackkent** [shedaniel/LightOverlay-Fabric#129] opened 2021-12-07 01:31 UTC
I generally use Optifine/Optifabric for my shaders and it's worked fine with LightOverlay for the last few versions; however, out of curiosity I decided to try out Iris (https://irisshaders.net) and Sodium (https://www.curseforge.com/minecraft/mc-mods/sodium/download/3542074) as an alternative to OF; it seems to work pretty well but I did notice that when I am using these two mods, pressing F7 for Light Overlay no longer seems to do anything. I'm not sure whether it's Iris or Sodium that's the culprit.

Not an emergency issue (and tbh I may stick with Optifine for now anyway) but I thought I would mention it!

Thanks for your work on this! It's one of my must-have mods. :)

**Comment by shedaniel** [comment] 2021-12-07 05:31
Duplicate of #5, this may be caused by how Iris modifies how things are rendered, unfortunately I am not an expert in this.

**Closed as completed** 2021-12-07 05:31 UTC
Labels: bug, duplicate
