### ISSUE TITLE
1.17.1 is not show

### ISSUE THREAD

**Issue by CtrlcCtrlVElite** [shedaniel/LightOverlay-Fabric#111] opened 2021-07-17 02:38 UTC
BSL 8.0.01
![image](https://user-images.githubusercontent.com/59501236/126022767-e9af20e3-4995-43ab-95b7-01302ecfdec2.png)

Original
![image](https://user-images.githubusercontent.com/59501236/126022807-a68fc11e-1d7d-45a7-8e4d-9c498772985a.png)

**Comment by shedaniel** [comment] 2021-07-17 02:40
Duplicate of #5

**Closed as completed by shedaniel** 2021-07-17 02:40 UTC
Labels: duplicate
